### ISSUE TITLE
Travis crashes when never run

### ISSUE THREAD

**Issue by jlmdegoede** [jlmdegoede/MOOCworkbench#76]
[2017-05-23 14:18:24,141: ERROR/PoolWorker-6] Task quality_manager.tasks.task_requirements_quality_check[732fb2ee-c4b9-4c29-8223-8b481c75017a] raised unexpected: TravisError('[404] not found',)
Traceback (most recent call last):
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/quality_manager/tasks.py", line 18, in task_requirements_quality_check
    req_measure.measure()
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/quality_manager/measurements/requirements_measurement.py", line 24, in measure
    last_build_log = travis_helper.get_log_for_last_build()
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/build_manager/travis_ci_helper.py", line 45, in get_log_for_last_build
    build = self.travis.build(self.travis_repo.last_build_id)
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/travispy/travispy.py", line 183, in build
    return Build.find_one(self._session, build_id)
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/travispy/entities/_entity.py", line 90, in find_one
    contents = get_response_contents(response)
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/travispy/_helpers.py", line 40, in get_response_contents
    raise TravisError(contents)
travispy.errors.TravisError: [404] not found
[2017-05-23 14:18:24,153: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: TravisError('[404] not found',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'travispy.errors.TravisError\'>: it\'s not the same object as travispy.errors.TravisError",)''.>
Traceback (most recent call last):
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/billiard/pool.py", line 363, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: TravisError('[404] not found',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'travispy.errors.TravisError\'>: it\'s not the same object as travispy.errors.TravisError",)''.

**Comment by jlmdegoede** [comment]
Fixed
