### ISSUE TITLE
Docs crash

### ISSUE THREAD

**Issue by jlmdegoede** [jlmdegoede/MOOCworkbench#77]
[2017-05-23 14:18:23,635: ERROR/PoolWorker-2] Task quality_manager.tasks.task_docs_coverage_check[a34d4531-5efb-4691-855c-79a736c49b2a] raised unexpected: TypeError('exceptions must derive from BaseException',)
Traceback (most recent call last):
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/docs_manager/sphinx_helper.py", line 93, in get_coverage_data
    coverage_list = pickle.load(open(coverage_pickle, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'github_repositories/jlmdegoede/Workbench-Python-Experiment/docs/_build/coverage/undoc.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/jochem/venvmooc/lib/python3.5/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/quality_manager/tasks.py", line 52, in task_docs_coverage_check
    docs_measure.measure()
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/quality_manager/measurements/docs_measurement.py", line 27, in measure
    coverage = sphinx_helper.get_coverage_data()
  File "/mnt/c/Users/joche/Documents/GitHub/MOOCworkbench/docs_manager/sphinx_helper.py", line 104, in get_coverage_data
    raise "Coverage data not found: {0}".format(e)
TypeError: exceptions must derive from BaseException

**Comment by jlmdegoede** [comment]
Fixed
